capability.py

Some "fan" domain devices, like the Xiaomi Air Purifier, have 3 modes: "auto", "silent" and "favorite". In this case, "favorite" mode should be mapped to "high fan speed" in Y smart home.

Added "favorite" as an alias for high fan speed

---

custom_components/yandex_smart_home/capability.py
custom_components/yandex_smart_home/prop.py

Correct processing of the 'relative' object in the request for changing the volume.
1. Даже если наш объект не объявлен, как relative, к нему может приходить запрос с параметром relative:true при управлении голосом, а не из Квазара.
2. Параметр 'value' в данном случае показывает на сколько шагов (задаётся в range.precision) надо увеличить или уменьшить громкость, в зависимости от знака параметра.

Correct processing of 'relative' object

---

README.md
custom_components/yandex_smart_home/capability.py
custom_components/yandex_smart_home/prop.py

Добавил выбор режима уборки (возможно, стоит обсудить список режимов, или вообще сделать его конфигурируемым из yaml);
Добавил свойство Батарея (пока только для домена vacuum);
Добавил возможность ставить уборку на паузу.
Теперь пылесос из hass имеет тот же функционал, что и проброшенный через облако Mija.
Тестировал это всё на Roborock S50.

Расширенная поддержка пылесосов

---

custom_components/yandex_smart_home/capability.py

Added support for target temperature precision for water_heater and climate integrations. Default is still 0.5

Temp precision support for water_heater and climate

---

custom_components/yandex_smart_home/capability.py

Fix when climate current mode is device state. That's why somebody always have the AC in Yandex shown in 'heat' mode, even if it's not.

Fix climate current mode (always shows "heat")

---

custom_components/yandex_smart_home/capability.py

Попросил Алису "выключить **всё** в прихожей", все устройства выключились, но туда поехал робот-пылесос, т.к. в прихожей была сущность script.vacuum_hallway.
Фикс, чтобы такого больше не случалось :)

Do not turn on scripts or scenes if they're actually asked to be turned off

---

README.md
custom_components/yandex_smart_home/capability.py

Не успел дотестить вовремя, чтобы включить всё в #104 :)
Добавляю пример конфига в README и поддержку пользотельского маппинга режимов работы.
Надеюсь, я правильно понял, как это делается в #98.
В интеграции `humidifier` можно использовать произвольный набор режимов. При этом есть несколько встроеных (самых частых) режимов, которые будут переводиться на другие языки, но требования ограничиваться этим списком нет. Этим `humidifier`, например, отличается от `climate`.
У Яндекса есть свой список, при этом расширять его нельзя, и маппировать 1:1 эти списки не получается.
Теперь маппирование будет происходить так:
1. Для каждого режима, если есть пользовательский маппинг в configuration.yaml - будет использоваться он
2. Затем будет использоваться встроенный маппинг для стандартных режимов
3. …

Add custom mode mapping support for humidifiers

---

README.md
custom_components/yandex_smart_home/prop.py

- Поддержка custom entity для давления
- Фикс величин - Яндекс ожидает в паскалях, HA отдает в гектапаскалях, поэтому умножаем на 100.
TODO можно попробовать поддержать другие величины - HA умеет еще мБар, Яндекс еще больше (атм, мбар, паскаль, мм рт ст). Но тут нужно подумать как грамотно конвертировать.
- Обновил ридми

Дополнительные фиксы для давления

---

custom_components/yandex_smart_home/http.py
custom_components/yandex_smart_home/prop.py

hass.data[DOMAIN] is shared data. Overwriting it here another modules of this component will not be able to use it. You should only access the elements you are working with, and not overwrite hass.data [DOMAIN] completely.
Contact sensor device_class not only `opening`, so added `door`, `garage_door`, `window`

Don't overwrite shared storage + Update ContactProperty

---

custom_components/yandex_smart_home/capability.py

Тут возможно ошибка: всегда вернется 0, если устройство доступно. 
Воспроизведется разумеется только если `channel_set_via_media_content_id: true`

Fix get value of ChannelCapability

---

custom_components/yandex_smart_home/notifier.py

После этого изменения ХА будет при запуске сам "пинать" УДЯ и он будет присылать запрос на обновление списка устройств. После чего, если есть новые (не удаленные, а абсолютно новые с точки зрения УДЯ) устройства приложение Яндекс должно прислать пуш о найденных устройствах. А сами устройства появятся в списке. Если удалить устройство из УДЯ и пытаться таким образом обновить список - ничего не произойдет - "старые" устройства придется как и раньше добавлять вручную, обновляя список через УДЯ.
https://yandex.ru/dev/dialogs/smart-home/doc/reference-alerts/post-skill_id-callback-discovery.html

Автоматическое обновление списка устройств при запуске Home Assistant

---

custom_components/yandex_smart_home/capability.py

Добавляет поддержку нового API для определения поддержки изменения цвета/температуры у лампочек (см. https://github.com/home-assistant/core/commit/5f2326fb5756b85255cec27d3b2172c44bc66058)
Старый подход не работает для интеграции с Tasmota, так как в ней более не устанавливают фичи SUPPORT_BRIGHTNESS и SUPPORT_COLOR

Поддержка нового API для цветных лампочек

---

custom_components/yandex_smart_home/notifier.py

This is the only place left where exception is silently ignored and we log useless `Error sending notification`. Switched to `.exception` to log Exception too.
Helps to debug: https://github.com/dmitry-k/yandex_smart_home/issues/203

Don't lose exception details on "Error sending notification"

---

custom_components/yandex_smart_home/prop.py

Яндекс [опубликовал](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/float-instance.html) документацию по датчикам качества воздуха. 
В соответствии с ней добавлены свойства PM1, PM2.5, PM10 и TVOC

Добавление датчиков качества воздуха

---

custom_components/yandex_smart_home/helpers.py
custom_components/yandex_smart_home/notifier.py

Для нотификатора сделана отдельная своя функция, где учитывается что если свойство не reportable - в ответе на запрос его не будет. 
Список свойств обрабатывается таким образом, чтобы в запросе было только то свойство, которое изменилось. Если оставлять как раньше - то датчики "без состояния покоя", такие как кнопка, датчик окна/двери и датчик движения будут слать ложное событие, если изменятся их другие атрибуты (например заряд батареи).

Доработка уведомлений

---

custom_components/yandex_smart_home/capability.py

В #214 была [замена](https://github.com/dmitry-k/yandex_smart_home/commit/e40db3fae97750d9e9ed07afca20145a3977e3f2#:~:text=and%20features%20%26%20light.-,SUPPORT_COLOR_TEMP,-return%20domain%20%3D%3D%20light) `SUPPORT_COLOR_TEMP` на `SUPPORT_COLOR`- я думаю это опечатка. 
Жаловались [тут](https://github.com/dmitry-k/yandex_smart_home/issues/226#issuecomment-871638069) и в чате ([1](https://t.me/yandex_smart_home/16), [2](https://t.me/yandex_smart_home/191)).
Также добавлялось умение temperature_k светильникам которые не умели в цветовую температуру.

Fix KeyError 'max_mireds'

---

custom_components/yandex_smart_home/helpers.py

Согласно [документации](https://yandex.ru/dev/dialogs/smart-home/doc/reference/post-devices-query.html#output-structure) `id` нужно обязательно указывать. Иначе, если провалиться в устройство - оно выглядит как доступное - УДЯ игнорирует его недоступность вследствие неправильного запроса.

Fix DEVICE_UNREACHABLE state

---

custom_components/yandex_smart_home/capability.py

Сейчас для BrightnessCapability минимальное значение 0. Однако, HA интерпретирует яркость 0 как необходимость полностью отключить светильник (т.е. вызывается light.turn_off). Поэтому при команде "Алиса, минимальная яркость света" лампочка выключится полностью (см. #244).
Кроме того, через интерфейс HA невозможно задать яркость < 1%. И в [примерах](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/device-type-light.html#device-type-light__exmples) из документации Яндекса min тоже 1.
Зависит от #248.
Fixes #244.

Не отключать светильники при установке минимальной яркости

---

custom_components/yandex_smart_home/capability.py

В текущей реализации для Яркости, Цвета и Температуры возвращаются нулевые значения если соответствующий атрибут у сущности пустой. Типичный пример - выключенный светильник.
Проблема в том, что "0" это совсем не "None" (а Яндекс в None не может как известно), в результате мы отправляем заведомо ложные данные. Ситуация особенно усугубляется например для температуры, для неё сейчас возвращается минимально возможное значение для этой сущности (т.е. возвращаем "теплый свет" когда лампочка выключена, хотя до выключения она могла была "холодной").
Предлагаю вообще не возвращать capability для None значений (поддержка была добавлена в #210). В этом случае Яндекс будет отображать последнее значение по этой capability. Например, при выключении светильника Яндекс будет показывать его последнюю …

Не возвращать "нулевые" значения для яркости, цвета и температуры

---

README.md
custom_components/yandex_smart_home/capability.py

Устраняет проблему, когда светильник поддерживает эффекты, но их названия не ложатся на маппинг сцен Яндекса. В этом случае светильник не передавался в Яндекс из-за пустого списка в параметре scenes для devices.capabilities.color_setting (при условии, что у светильник не поддерживает rgb и температуру).
Плюс добавлен пример настройки сцен в README.
Должно помочь для #249 и #216.

Рефакторинг сцен для светильников

---

README.md
custom_components/yandex_smart_home/__init__.py
custom_components/yandex_smart_home/const.py
custom_components/yandex_smart_home/notifier.py

В УДЯ есть [возможность](https://yandex.ru/dev/dialogs/alice/doc/access.html) делиться навыком УД с другими пользователями. Также можно создать 2 и более одинаковых навыков у разных пользователей Яндекса (но это не всегда корректно работает).
Для отправки данных 2 и более навыкам нужно токен для каждого из них, ID навыка, а также ID пользователей ХА которым соответствуют пользователи Яндекса. То есть те же данные, только для каждого из навыков/пользователей.
Эти данные нужно заполнить списком:
```
yandex_smart_home:
notifier:
- oauth_token: XXXXXXXXXXXXXXXXXXXXXXXXXXX
skill_id: xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
user_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
- oauth_token: YYYYYYYYYYYYYYYYYYYYYYYYYYY
skill_id: yyyyyyyy-yyyy-yyyy-yyyyyyyyyyyy
user_id: yyyyyyyyyyyyyyyyyyyyyyyyyyyy
```
Настройка в …

Уведомление нескольких навыков/пользователей

---

custom_components/yandex_smart_home/capability.py
custom_components/yandex_smart_home/const.py

Увлажнители Xiaomi, подключенные через интеграцию [xiaomi_airpurifier](https://github.com/syssi/xiaomi_airpurifier), находятся в домене `fan`. Поэтому установка влажности штатным сервисом `humidifer.set_humidity` для них не будет работать.
Этот пулл реквест добавляет поддержку установки влажности для таких увлажнителей.

Возможность управлять влажностью для увлажнителей Xiaomi

---

custom_components/yandex_smart_home/capability_custom.py

В случае с использованием select в качестве переключателя в HA - состояние кастомного тоггла в УДЯ не определяется и всегда `false` 
Данное изменение решает проблему инвертируя логику получения статуса с "`if true`" на "`if not false`"
на скрине пример конфигурации которая неверно работает в текущей версии

Inverted logic for getting the state of toggle

---

custom_components/yandex_smart_home/capability_mode.py

Due to a spelling error in the "Miot Auto" integration, the "slient" state has been added.

Silent and Slient added
