dext0r/yandex_smart_home

README.markdown
capability.py
helpers.py

Добавлена возможность работы с пылесосом как с выключателем: Включи пылесос, выключи пылесос.
Тестировал на xiaomi vacuum 1.

Работа с типом "пылесос"

---

capability.py

Fixes crash in HA 0.96 ( #22 ) and adds support for the new HA Climate 1.0 component.
HA pull request: home-assistant/home-assistant#23899

 Support for HA Climate 1.0

---

README.md
custom_components/yandex_smart_home/capability.py
custom_components/yandex_smart_home/const.py

water_heater domain support added

Add support for water_heater

---

custom_components/yandex_smart_home/prop.py

Add 'battery_level' and 'amperage' to instance_unit in class CustomEntityProperty.
Добавление датчикам функций **amperage** и **battery_level**.

Add 'battery_level' and 'amperage'

---

README.md
custom_components/yandex_smart_home/prop.py

Add 'battery_level' and 'amperage' in readme.md

Actualization readme

---

custom_components/yandex_smart_home/capability.py

Added speed capabilitys for Xiaomi zhimi.fan.v3 and possibly for other models.
Issue #65

Add support for Xiaomi Zhimi fan

---

custom_components/yandex_smart_home/prop.py

Report actual errors to Yandex cloud so broken devices report their real status in Quasar.

Improve handling of unexistent/unready/broken entities

---

custom_components/yandex_smart_home/capability.py

Так как никто не откликнулся, пришлось ковырять самому :)

Возможность установки уровня штор в %

---

custom_components/yandex_smart_home/const.py

Added sensors as standalone device and some other devices

New Yandex device types (sensors)

---

custom_components/yandex_smart_home/capability.py
custom_components/yandex_smart_home/helpers.py

Фикс бага https://github.com/dmitry-k/yandex_smart_home/issues/127 , немного улучшил код https://github.com/dmitry-k/yandex_smart_home/pull/134/ проверил, работает: включает, выключает свет и яркость уменьшает, увеличивает и можно задать определенную яркость, например 80%

fix Alice cannot decrease / increase brightness, and more info about devices

---

custom_components/yandex_smart_home/helpers.py
custom_components/yandex_smart_home/smart_home.py

Улучшенный фикс этого бага https://github.com/dmitry-k/yandex_smart_home/issues/132

Улучшение определения производителя и модели устройства

---

custom_components/yandex_smart_home/prop.py

Функция теперь выдает только True/False
А раньше выдавала все что угодно почему-то.. Хотя вроде бы все было верно.
Без этого исправления в УДЯ невозможно зайти в устройство, в котором прописаны property типа bool
Спасибо @alphasixtyfive за подсказку =)

Property bool value fix

---

custom_components/yandex_smart_home/prop.py

https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/bool-instance.html#bool-instance__contact

Yandex API Updated: Magnet -> Contact

---

custom_components/yandex_smart_home/prop.py

Yandex supports pressure sensors, this integration does not. Let's fix this.

Add pressure sensor property

---

custom_components/yandex_smart_home/notifier.py

Плохо фильтровались состояния STATE_UNAVAILABLE и STATE_UNKNOWN 
Поправил - должно решить проблему %)
Fix #177

Исправление фильтра состояний для отправки уведомления

---

custom_components/yandex_smart_home/capability.py

@dmitry-k давайте закроем еще один PR, а то товарищ @ckesc забыл видимо ;)
Fix  #168 #165

Support closing window by some number

---

custom_components/yandex_smart_home/capability.py

Табуляция случайно пробралась в файл. @dmitry-k я поторопился и снова накосячил =( Простите

Fix indentation

---

custom_components/yandex_smart_home/prop.py

Константы упорядочены как в homeassistant/const.py
Удален импорт констант из binary_senor.

Упорядочивание констант в prop.py

---

custom_components/yandex_smart_home/prop.py

Датчик CO2 - строка заменена константой, добавлена возможность читать данные из домена fan
У датчика потребляемой мощности удален домен light - в некоторых случаях это вызывало ошибку если в атрибутах дублировалось состояние светильника (power: on)
Для датчика уровня батареи исключена возможность обработки датчика низкого заряда - для него теперь есть бинарник.
В датчике движения добавлена возможность завести как ДД другие датчики присутствия.

Доработка и исправление прочих датчиков

---

custom_components/yandex_smart_home/capability.py

Некоторые светильники (например созданные через template) поддерживают только HS режим цвета. Этот патч добавляет его поддержку.
Должен помочь для #216.

Поддержка режима цвета HS для цветных светильников

---

custom_components/yandex_smart_home/__init__.py

Исправление проблемы с обязательным требованием заполнения раздела notifier

Fix notifier

---

custom_components/yandex_smart_home/capability.py

В home-assistant/core#45407 было принято решение избавиться от метода `fan.set_speed` и использовать вместо него `fan.set_percentage` или `fan.set_preset_mode`.
Этот пулл реквест реализует переключение скоростей вентилятора через пресеты (`fan.set_preset_mode`) в `FanSpeedCapability`. Совместимость с устройствами, не умеющими пресеты остается, но в логах будет deprecation warning, это нормально.
Fixes #212, #242

Поддержка пресетов для вентилятора вместо скоростей

---

custom_components/yandex_smart_home/prop.py

Конвертация значения из ppb в μg/m3

Added conversion of tVOC value from ppb to μg/m3

---

docs/advanced-settings.md
docs/config-example.yaml
tests/fixtures/valid-config.yaml

Исправлено написание 'Гостиная' в доках. В некоторых местах написано верно, а в некоторых - нет

'Гостин[н]ая' spelling fixed

---

custom_components/yandex_smart_home/capability_mode.py

Update mapping for vacuum modes created by component Deebot 4 Home Assistant (https://github.com/DeebotUniverse/Deebot-4-Home-Assistant)

Deebot 4 Home Assistant vacuum mapping update
